### ISSUE TITLE
Does not work with pathogen

### ISSUE THREAD

**Issue by zardilior** [prashanthellina/follow-markdown-links#7]
Followed instructions and it is not working

**Comment by desdic** [comment]
I have the same issue

**Comment by utix** [comment]
I realize that the `autocmd` wasn't working, I just add 
```
autocmd FileType markdown nnoremap <script> <CR> :FollowLink<CR>
autocmd FileType markdown nnoremap <script> <BS> :e#<CR>
```
on my vimrc and it was working well.
This is clearly not the fix, but a workaround

**Comment by utix** [comment]
@prashanthellina not fixed for me, I still need to add the autocmd lines on my vimrc

Using VIM - Vi IMproved 8.1
